# Elasticsearch конфигурация для ERNI-KI
# Оптимизированная настройка для централизованного хранения логов

# ============================================================================
# ОСНОВНЫЕ НАСТРОЙКИ КЛАСТЕРА
# ============================================================================

# Имя кластера
cluster.name: erni-ki-logs

# Имя узла
node.name: erni-ki-elasticsearch-01

# Роли узла
node.roles: [ master, data, ingest ]

# ============================================================================
# СЕТЕВЫЕ НАСТРОЙКИ
# ============================================================================

# Привязка к интерфейсам
network.host: 0.0.0.0

# HTTP порт
http.port: 9200

# Transport порт
transport.port: 9300

# ============================================================================
# НАСТРОЙКИ DISCOVERY
# ============================================================================

# Тип discovery для single-node кластера
discovery.type: single-node

# Начальные master узлы
cluster.initial_master_nodes: ["erni-ki-elasticsearch-01"]

# ============================================================================
# НАСТРОЙКИ ПАМЯТИ И ПРОИЗВОДИТЕЛЬНОСТИ
# ============================================================================

# Отключение swap
bootstrap.memory_lock: true

# Настройки индексирования
indices.memory.index_buffer_size: 20%
indices.memory.min_index_buffer_size: 96mb

# Настройки fielddata
indices.fielddata.cache.size: 40%

# Настройки запросов
indices.queries.cache.size: 10%

# ============================================================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ
# ============================================================================

# Отключение X-Pack Security для упрощения (в продакшене включить!)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Отключение мониторинга X-Pack
xpack.monitoring.collection.enabled: false

# Отключение машинного обучения
xpack.ml.enabled: false

# Отключение Watcher
xpack.watcher.enabled: false

# ============================================================================
# НАСТРОЙКИ ИНДЕКСОВ
# ============================================================================

# Автоматическое создание индексов
action.auto_create_index: true

# Настройки шардов по умолчанию
index.number_of_shards: 1
index.number_of_replicas: 0

# Настройки refresh
index.refresh_interval: 30s

# Максимальное количество полей в индексе
index.mapping.total_fields.limit: 2000

# ============================================================================
# НАСТРОЙКИ ЛОГИРОВАНИЯ
# ============================================================================

# Уровень логирования
logger.level: INFO

# Логирование медленных запросов
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.query.debug: 2s
index.search.slowlog.threshold.query.trace: 500ms

index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 800ms
index.search.slowlog.threshold.fetch.debug: 500ms
index.search.slowlog.threshold.fetch.trace: 200ms

# Логирование медленного индексирования
index.indexing.slowlog.threshold.index.warn: 10s
index.indexing.slowlog.threshold.index.info: 5s
index.indexing.slowlog.threshold.index.debug: 2s
index.indexing.slowlog.threshold.index.trace: 500ms

# ============================================================================
# НАСТРОЙКИ ХРАНЕНИЯ
# ============================================================================

# Путь к данным
path.data: /usr/share/elasticsearch/data

# Путь к логам
path.logs: /usr/share/elasticsearch/logs

# ============================================================================
# НАСТРОЙКИ ИНДЕКСНЫХ ШАБЛОНОВ
# ============================================================================

# Автоматическое применение шаблонов
index.template.auto_create: true

# ============================================================================
# НАСТРОЙКИ ПРОИЗВОДИТЕЛЬНОСТИ
# ============================================================================

# Настройки thread pool
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000
thread_pool.get.queue_size: 1000

# Настройки circuit breaker
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# ============================================================================
# НАСТРОЙКИ МОНИТОРИНГА
# ============================================================================

# HTTP CORS для Grafana и других инструментов
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, Content-Type, Content-Length, Authorization

# ============================================================================
# НАСТРОЙКИ RETENTION POLICY
# ============================================================================

# Автоматическое удаление старых индексов (через ILM)
# Настраивается через API или Kibana

# ============================================================================
# ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ
# ============================================================================

# Отключение телеметрии
telemetry.enabled: false

# Настройки компрессии
index.codec: best_compression

# Настройки merge policy
index.merge.policy.max_merge_at_once: 10
index.merge.policy.segments_per_tier: 10

# Настройки translog
index.translog.flush_threshold_size: 512mb
index.translog.sync_interval: 5s
