# Checkov Configuration
# Suppress specific checks that are false positives or not applicable to our use case

# CKV_GHA_7: Allow workflow_dispatch inputs for controlled deployment workflows
# These inputs are used for environment selection and are properly validated
skip-check:
  - CKV_GHA_7 # workflow_dispatch inputs are acceptable for our deployment automation

  # CKV_DOCKER_2: HEALTHCHECK not required for all containers
  # Some containers (exporters, sidecars) don't need health checks
  - CKV_DOCKER_2 # HEALTHCHECK will be added where appropriate
