# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration - ERNI-KI Project
# Docs: https://docs.coderabbit.ai/reference/configuration

language: en
tone_instructions: "Be constructive and specific. Focus on security, performance, and maintainability."
early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "## Change Overview"
  auto_title_placeholder: "### CodeRabbit Review"
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  changed_files_summary: true
  abort_on_close: true
  estimate_code_review_effort: true
  suggested_labels: true
  suggested_reviewers: true
  labeling_instructions:
    - label: "security"
      instructions: "Apply to PRs with changes to authentication, secrets, or security"
    - label: "breaking-change"
      instructions: "Apply if changes break API backward compatibility"
    - label: "documentation"
      instructions: "Apply to PRs with documentation-only changes"

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - main
      - develop
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "wip"
      - "[skip ci]"
      - "[no review]"

  # Tools configuration - enable relevant linters
  tools:
    # Python
    ruff:
      enabled: true
    pylint:
      enabled: false # Using ruff instead
    # JavaScript/TypeScript
    eslint:
      enabled: true
    biome:
      enabled: false # Using eslint
    # Shell
    shellcheck:
      enabled: true
    # Docker/Infrastructure
    hadolint:
      enabled: true
    checkov:
      enabled: true
    # Security
    gitleaks:
      enabled: true
    semgrep:
      enabled: true
    # Go
    golangci-lint:
      enabled: true
    # YAML
    yamllint:
      enabled: true
    # Markdown
    markdownlint:
      enabled: true
    languagetool:
      enabled: false # Disable grammar check for code repos

  path_instructions:
    - path: "**/*.go"
      instructions: |
        - Check for Go idioms compliance
        - Ensure error handling (don't ignore err)
        - Check for goroutine leaks
        - Validate context usage
        - Check defer for cleanup operations
    - path: "**/*.py"
      instructions: |
        - Check PEP 8 and Ruff rules compliance
        - Ensure type hints for public functions
        - Check exception handling (don't use bare except)
        - Validate logging usage instead of print
        - Check for SQL injection and other vulnerabilities
    - path: "**/*.ts"
      instructions: |
        - Check strict typing (avoid any)
        - Ensure error handling in async functions
        - Validate null/undefined checks
        - Check for XSS vulnerabilities
    - path: "**/*.sh"
      instructions: |
        - Check for set -euo pipefail usage
        - Ensure proper variable quoting ("$var")
        - Check error handling and exit codes
        - Validate shellcheck directive usage
    - path: ".github/workflows/**"
      instructions: |
        - Check secrets security (don't log them)
        - Ensure timeout-minutes is present
        - Validate minimal permissions
        - Check action version pinning (SHA)
        - Ensure GITHUB_TOKEN usage instead of PAT where possible
    - path: "**/Dockerfile*"
      instructions: |
        - Check for specific image versions (not latest)
        - Ensure multi-stage builds for size reduction
        - Check for non-root user execution
        - Validate HEALTHCHECK instruction
        - Check for secrets in image
    - path: "compose.yml"
      instructions: |
        - Check image version pinning
        - Ensure health checks are present
        - Check resource limits (mem_limit, cpus)
        - Validate secrets usage instead of environment
        - Check restart policy
    - path: "**/*.yaml"
      instructions: |
        - Check YAML syntax correctness
        - Ensure consistent indentation
        - Validate required fields presence
    - path: "tests/**"
      instructions: |
        - Check edge case coverage
        - Ensure test isolation
        - Validate mock/stub usage
        - Check for assertions presence
    - path: "docs/**/*.md"
      instructions: |
        - Check markdown syntax correctness
        - Ensure links are working
        - Validate frontmatter presence where required

  path_filters:
    - "!**/*.lock"
    - "!**/*.sum"
    - "!**/package-lock.json"
    - "!**/bun.lockb"
    - "!docs/locales/**"
    - "!scripts/archon/**"
    - "!site/**"
    - "!coverage/**"
    - "!htmlcov/**"
    - "!node_modules/**"
    - "!.venv/**"
    - "!**/*.min.js"
    - "!**/*.min.css"

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto
  code_guidelines:
    enabled: true
    file_patterns:
      - "CLAUDE.md"
      - "CONTRIBUTING.md"
      - "docs/development/**/*.md"

code_generation:
  docstrings:
    enabled: true
    language: en
  unit_tests:
    enabled: true
    path_instructions:
      - path: "**/*.py"
        instructions: "Use pytest with fixtures and parametrize"
      - path: "**/*.ts"
        instructions: "Use Vitest with describe/it structure"
      - path: "**/*.go"
        instructions: "Use standard testing package with table-driven tests"
