# golangci-lint configuration for erni-ki project
# yaml-language-server: $schema=
# Linter configuration for Go code

# golangci-lint configuration version

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

# output: section removed - output settings are now managed via CLI flags

linters-settings:
  # Settings for various linters
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf

  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be too strict

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: main

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  gofumpt:
    extra-rules: true

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Errors unhandled (too strict for some cases)

  gosimple:
    checks: ["all"]

  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "deprecated, use google.golang.org/protobuf"

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all"]

  whitespace:
    multi-if: false
    multi-func: false

  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    allow-separated-leading-comment: false

linters:
  enable:
    # Basic linters
    - errcheck # Error handling check
    - gosimple # Code simplification
    - govet # Static analysis
    - ineffassign # Unused assignments
    - staticcheck # Static analysis
    - typecheck # Type checking
    - unused # Unused code

    # Additional linters
    - asciicheck # ASCII characters check
    - bodyclose # HTTP body close check
    - dogsled # Blank identifiers check
    - dupl # Code duplication
    - durationcheck # time.Duration check
    - errorlint # Error check
    - exhaustive # Switch statements check
    - gochecknoinits # Init functions check
    - gochecknoglobals # Global variables check
    - gocognit # Cognitive complexity
    - goconst # Repeated strings
    - gocritic # Multiple checks
    - gocyclo # Cyclomatic complexity
    - godot # Comments should end with a dot
    - gofmt # Formatting
    - gofumpt # Strict formatting
    - goimports # Imports
    - gomodguard # Module blocking
    - goprintffuncname # Printf functions
    - gosec # Security
    - lll # Line length
    - makezero # Make check
    - misspell # Spelling
    - nakedret # Naked returns
    - nilerr # Nil errors
    - noctx # HTTP requests without context
    - nolintlint # nolint directives check
    - prealloc # Memory pre-allocation
    - predeclared # Predeclared identifiers
    - revive # golint replacement
    - rowserrcheck # SQL rows.Err()
    - sqlclosecheck # SQL Close()
    - stylecheck # Code style
    - tparallel # Parallel tests
    - unconvert # Unnecessary conversions
    - unparam # Unused parameters
    - wastedassign # Wasted assignments
    - whitespace # Whitespace

  disable:
    # Disabled linters (can be too strict)
    - cyclop # Cyclomatic complexity (duplicates gocyclo)
    - forbidigo # Function prohibition
    - funlen # Function length (can be too strict)
    - gci # Imports (can conflict with goimports)
    - godox # Disabled: TODO comments are tracked via pre-commit hooks
    - nestif # If nesting
    - paralleltest # Parallel tests (can be excessive)
    - testpackage # Test packages
    - varnamelen # Variable name length
    - wrapcheck # Error wrapping
    - wsl # Whitespace (can be too strict)

issues:
  # Max issues per linter
  max-issues-per-linter: 0
  # Max same issues
  max-same-issues: 0
  # Show only new issues
  new: false

severity:
  # Default severity level
  default-severity: error
