---
# yamllint configuration for documentation frontmatter

extends: default

rules:
  # Line length - allow long lines in documentation
  line-length:
    max: 120
    level: warning

  # Document start - require --- for frontmatter
  document-start:
    present: true

  # Indentation - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments - allow comments without space after #
  comments:
    min-spaces-from-content: 1

  # Truthy values - allow yes/no, true/false, on/off
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

  # Empty lines
  empty-lines:
    max: 2

ignore: |
  node_modules/
  .venv/
  venv/
  site/
  .git/
  *.json
