# Simplified Alertmanager Configuration для ERNI-KI
# Упрощенная конфигурация обработки алертов

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@erni-ki.local'
  resolve_timeout: 5m

# Маршрутизация алертов
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'erni-ki-webhook'
  
  routes:
    # Критические алерты
    - match:
        severity: critical
      receiver: 'erni-ki-critical'
      group_wait: 0s
      group_interval: 5s
      repeat_interval: 15m
      
    # Предупреждения
    - match:
        severity: warning
      receiver: 'erni-ki-warning'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

# Получатели уведомлений
receivers:
  # Webhook получатель по умолчанию
  - name: 'erni-ki-webhook'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook'
        send_resolved: true

  # Критические алерты
  - name: 'erni-ki-critical'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook/critical'
        send_resolved: true

  # Предупреждения
  - name: 'erni-ki-warning'
    webhook_configs:
      - url: 'http://webhook-receiver:9093/webhook/warning'
        send_resolved: true

# Подавление алертов
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'component']
