name: "Setup Python Environment"
description: "Setup Python with pip caching and install dependencies"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.11"
  requirements-file:
    description: "Requirements file to install"
    required: false
    default: "requirements-dev.txt"
  install-deps:
    description: "Whether to install dependencies"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: ${{ inputs.requirements-file }}

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements-file }}
