# Alertmanager configuration для проекта erni-ki
# Правила алертинга и уведомлений

global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@erni-ki.local"
  smtp_auth_username: ""
  smtp_auth_password: ""
  smtp_require_tls: false

# Шаблоны для уведомлений
templates:
  - "/etc/alertmanager/templates/*.tmpl"

# Маршрутизация алертов
route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "default-receiver"

  routes:
    # Критические алерты - немедленно
    - match:
        severity: critical
      receiver: "critical-alerts"
      group_wait: 0s
      repeat_interval: 5m

    # Алерты по сервисам AI
    - match_re:
        service: (ollama|openwebui|auth)
      receiver: "ai-services-alerts"
      group_interval: 5m

    # Алерты инфраструктуры
    - match_re:
        service: (nginx|postgres|redis|cloudflared)
      receiver: "infrastructure-alerts"
      group_interval: 10m

    # Алерты безопасности
    - match:
        category: security
      receiver: "security-alerts"
      group_wait: 0s
      repeat_interval: 30m

# Подавление дублирующихся алертов
inhibit_rules:
  # Подавляем warning если есть critical
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]

  # Подавляем алерты о недоступности если сервис down
  - source_match:
      alertname: "ServiceDown"
    target_match_re:
      alertname: "(HighLatency|HighErrorRate)"
    equal: ["instance"]

# Получатели уведомлений
receivers:
  # Получатель по умолчанию
  - name: "default-receiver"
    webhook_configs:
      - url: "http://webhook-receiver:9093/webhook"
        send_resolved: true
        http_config:
          basic_auth:
            username: "admin"
            password: "webhook-secret"

  # Критические алерты
  - name: "critical-alerts"
    webhook_configs:
      - url: "http://webhook-receiver:9093/webhook/critical"
        send_resolved: true

  # Алерты AI сервисов
  - name: "ai-services-alerts"
    webhook_configs:
      - url: "http://webhook-receiver:9093/webhook/warning"
        send_resolved: true

  # Алерты инфраструктуры
  - name: "infrastructure-alerts"
    webhook_configs:
      - url: "http://webhook-receiver:9093/webhook/warning"
        send_resolved: true

  # Алерты безопасности
  - name: "security-alerts"
    webhook_configs:
      - url: "http://webhook-receiver:9093/webhook/critical"
        send_resolved: true
# Конфигурация веб-интерфейса задается через command line аргументы в docker-compose
