# Shared ERNI-KI status block used in README and MkDocs (Wave 1)
date: "2025-12-15"
release: "Production Ready v0.61.3"
containers: "34/34 services healthy"
grafana_dashboards: "5/5 Grafana dashboards (provisioned)"
prometheus_alerts: "20 Prometheus alert rules active"
gpu_stack: "Ollama 0.13.0 + OpenWebUI v0.6.40 (GPU)"
ai_stack: "LiteLLM v1.80.0-stable.1 + Context7, Docling, Tika, EdgeTTS"
monitoring_stack: "Prometheus v3.7.3, Grafana v12.3.0, Loki v3.6.2, Fluent Bit v4.2.0, Alertmanager v0.29.0"
automation: "Cron: PostgreSQL VACUUM 03:00, Docker cleanup 04:00, Backrest 01:30, Watchtower selective updates"
notes: "Compose-synced: searxng 2025.11.21, cloudflared 2025.11.1, Tika 3.2.3.0-full, exporters hardened"
